import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Aside} from "../components/Aside";
import {Toaster} from "../components/ui/toaster";
import {ThemeProvider} from "../components/theme-provider";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {

  title: "Create Next App",
  description: "Generated by create next app",
  openGraph:{
    title: "Poe Build Cost",
    type: "website",
    url: "https://www.poebuildcost.com",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const GA_MEASUREMENT_ID = process.env.NEXT_PUBLIC_MEASUREMENT_ID;
  const ADSENSE_ACCOUNT = process.env.NEXT_PUBLIC_ADSENSE_ACCOUNT

  return (
    <html lang="en">
      <body className={inter.className}>
      <meta name="google-adsense-account" content={ADSENSE_ACCOUNT} />

      <script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
      />
      <script
          dangerouslySetInnerHTML={{
            __html: `
                      window.dataLayer = window.dataLayer || [];
                      function gtag(){dataLayer.push(arguments);}
                      gtag('js', new Date());
                      gtag('config', '${GA_MEASUREMENT_ID}', {
                        page_path: window.location.pathname,
                      });
                    `,
          }}
      />
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
          <Aside/>
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
