name: CI/CD

on:
  push:
    branches:
      - main

env:
  LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHT_SSH }}
  LIGHTSAIL_HOST: ${{ secrets.LIGHT_URL }}
  LIGHTSAIL_USERNAME: ec2-user
  AWS_REGION: ap-northeast-2

  NEXT_PUBLIC_MEASUREMENT_ID: ${{secrets.NEXT_PUBLIC_MEASUREMENT_ID}}
  NEXT_PUBLIC_ADSENSE_ACCOUNT: ${{secrets.NEXT_PUBLIC_ADSENSE_ACCOUNT}}
  NEXT_PUBLIC_POBCODE_REQ_URL: ${{secrets.NEXT_PUBLIC_POBCODE_REQ_URL}}
  NEXT_PUBLIC_DESTINATION: ${{secrets.NEXT_PUBLIC_DESTINATION}}
  NEXT_PUBLIC_SOURCE: ${{secrets.NEXT_PUBLIC_SOURCE}}
  NEXT_PUBLIC_TRADESEARCH: ${{secrets.NEXT_PUBLIC_TRADESEARCH}}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: 해당 브런치로 체크아웃
        uses: actions/checkout@v2

      - name: 노드 설치
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: 프로젝트 디펜던시 설치
        run: yarn

      - name: env 만들기
        run: |
          echo "NEXT_PUBLIC_MEASUREMENT_ID=$NEXT_PUBLIC_MEASUREMENT_ID" >> .env
          echo "NEXT_PUBLIC_ADSENSE_ACCOUNT=$NEXT_PUBLIC_ADSENSE_ACCOUNT" >> .env
          echo "NEXT_PUBLIC_POBCODE_REQ_URL=$NEXT_PUBLIC_POBCODE_REQ_URL" >> .env
          echo "NEXT_PUBLIC_DESTINATION=$NEXT_PUBLIC_DESTINATION" >> .env
          echo "NEXT_PUBLIC_SOURCE=$NEXT_PUBLIC_SOURCE" >> .env
          echo "NEXT_PUBLIC_TRADESEARCH=$NEXT_PUBLIC_TRADESEARCH" >> .env


      - name: 프로젝트 빌드하기
        run: yarn build

      - name: 빌드 파일 생성 체크
        run: ls .. -al

      - name: AWS 인증하기
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_P }}
          aws-secret-access-key: ${{ secrets.AWS_PR }}
    
      - name: AWS Lightsail
        run: aws configure list
    
      - name: 배포 자동화
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHT_URL }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHT_SSH }}
          source: './'
          strip_components: 1
          target: '/home/ec2-user/buildscost/front/'
          
      - name: Restart PM2 process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHT_URL }}
          username: ${{env.LIGHTSAIL_USERNAME}}
          key: ${{ secrets.LIGHT_SSH }}
          script: cd /home/ec2-user/buildscost/front&pm2 restart front 
